version: '3'

services:
  void-src-addon:
    build: .
    ports:
      - "4477:7000"
    restart: unless-stopped
    environment:
      - PORT=7000 

  localxpose:
    image: localxpose/localxpose:latest
    restart: unless-stopped
    environment:
      - ACCESS_TOKEN=Wei8j6S0x0O6sagwRbIiTRBOZAzldbeLGgzVQrHA
    command: tunnel http --to void-src-addon:7000
    depends_on:
      - void-src-addon 